// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPW9ZYCqiuys_MqjZrI6wybUXL9hzqQ50',
    appId: '1:529426925841:web:c312c449905626171da4b0',
    messagingSenderId: '529426925841',
    projectId: 'speats-f09a6',
    authDomain: 'speats-f09a6.firebaseapp.com',
    storageBucket: 'speats-f09a6.firebasestorage.app',
    measurementId: 'G-LDLB9M4PH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTjx52lrLl2-9wP4SIK6yO0OHgEuVa-SI',
    appId: '1:529426925841:android:024750b89c2d6d8b1da4b0',
    messagingSenderId: '529426925841',
    projectId: 'speats-f09a6',
    storageBucket: 'speats-f09a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPW9ZYCqiuys_MqjZrI6wybUXL9hzqQ50',
    appId: '1:529426925841:web:6c5cf46ac12fc83e1da4b0',
    messagingSenderId: '529426925841',
    projectId: 'speats-f09a6',
    authDomain: 'speats-f09a6.firebaseapp.com',
    storageBucket: 'speats-f09a6.firebasestorage.app',
    measurementId: 'G-WB7S2RR5HG',
  );
}
